name: whisper_wrapper
description: Offline, on-device speech recognition for Flutter powered by whisper.cpp.
version: 3.0.3
repository: https://github.com/core-laboratories/whisper_wrapper
homepage: https://github.com/core-laboratories/whisper_wrapper
issue_tracker: https://github.com/core-laboratories/whisper_wrapper/issues

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.1.4
  ffmpeg_kit_flutter_new_min: ^3.6.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  plugin_platform_interface: ^2.1.8
  universal_io: ^2.2.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  ffigen: ^21.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  very_good_analysis: ^10.3.0

topics:
  - speech-recognition
  - offline
  - whisper
  - machine-learning

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      linux:
        ffiPlugin: true
